// GENERATED by tools/port_planbound_engine.py from design/planbound-site.html (script #11).
// The body below is the original running code. Do not hand-edit; re-run the generator.
/* eslint-disable */
export default function installTree(THREE) {
window.PB.initTree=function(){

(function(){
'use strict';
const PB=window.PB;if(!PB.webgl||!PB.globe)return;
const g=PB.globe,random=PB.rng(0x5EED),V=THREE.Vector3,attractors=[],nodes=[{p:new V(0,0,0),parent:-1,depth:0,children:[],r:.004}],dI=1.05,dK=.08,step=.06;
const hub=g.hubs.geometry.attributes.position.array;
for(let i=0;i<150;i++)attractors.push({p:new V(hub[i*3],hub[i*3+1],hub[i*3+2]).multiplyScalar(2/g.R),hub:i,alive:true});
for(let i=0;i<500;i++){const z=random()*2-1,a=random()*Math.PI*2,r=1.2+random()*.8,s=Math.sqrt(1-z*z);attractors.push({p:new V(Math.cos(a)*s*r,z*r,Math.sin(a)*s*r),hub:-1,alive:true})}
// A radial seed scaffold provides outward starts; all following growth is attraction driven.
for(let i=0;i<6;i++){const direction=attractors[i*23].p.clone().normalize();let parent=0;for(let s=1;s<=10;s++){const id=nodes.length;nodes.push({p:direction.clone().multiplyScalar(s*step),parent,depth:s,children:[],r:.004});nodes[parent].children.push(id);parent=id}}
const occupied=new Set(nodes.map(n=>[n.p.x,n.p.y,n.p.z].map(v=>Math.round(v*1000)).join(',')));
let iteration=0,complete=false;
function cell(x,y,z){return x+','+y+','+z}
function growStep(){const buckets=new Map();for(let i=0;i<nodes.length;i++){const p=nodes[i].p,key=cell(Math.floor(p.x/dI),Math.floor(p.y/dI),Math.floor(p.z/dI));if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(i)}const directions=new Map();let active=0;
 for(let i=0;i<attractors.length;i++){const a=attractors[i];if(!a.alive)continue;active++;const p=a.p,cx=Math.floor(p.x/dI),cy=Math.floor(p.y/dI),cz=Math.floor(p.z/dI);let near=-1,best=dI*dI;
  for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++){const b=buckets.get(cell(cx+x,cy+y,cz+z));if(!b)continue;for(let j=0;j<b.length;j++){const id=b[j],dist=p.distanceToSquared(nodes[id].p);if(dist<best){best=dist;near=id}}}
  if(near<0)continue;if(best<dK*dK){a.alive=false;continue}let direction=directions.get(near);if(!direction){direction=new V();directions.set(near,direction)}direction.add(p.clone().sub(nodes[near].p).normalize());
 }
 if(!active||!directions.size)return false;
 let added=0;for(const [parent,direction] of directions){if(nodes.length>=5600)break;direction.normalize().addScaledVector(nodes[parent].p,.03).normalize();const p=nodes[parent].p.clone().addScaledVector(direction,step);if(p.length()>2.05)continue;const key=[p.x,p.y,p.z].map(v=>Math.round(v*1000)).join(',');if(occupied.has(key))continue;occupied.add(key);added++;const id=nodes.length;nodes.push({p,parent,depth:nodes[parent].depth+1,children:[],r:.004});nodes[parent].children.push(id)}return added>0&&nodes.length<5600;
}
function chunk(){const start=performance.now();do{if(iteration++>=420||!growStep()){complete=true;break}}while(performance.now()-start<5);if(!complete){requestAnimationFrame(chunk);return}finish()}
function finish(){
 PB.activeScope=PB.lifecycle.heroScope;
 for(let i=nodes.length-1;i>=0;i--){const n=nodes[i];if(n.children.length){let sum=0;for(let j=0;j<n.children.length;j++)sum+=Math.pow(nodes[n.children[j]].r,2.5);n.r=Math.min(.05,Math.pow(sum,1/2.5))}}
 const terminals=[];for(let i=0;i<nodes.length;i++)if(!nodes[i].children.length&&nodes[i].p.length()>1.1)terminals.push(i);
 // Attach each original hub identity to its nearest terminal, then farthest-point sample.
 const hubTerminals=[];for(let h=0;h<150;h++){let best=Infinity,id=0;for(let j=0;j<terminals.length;j++){const d=attractors[h].p.distanceToSquared(nodes[terminals[j]].p);if(d<best){best=d;id=terminals[j]}}if(!hubTerminals.includes(id))hubTerminals.push(id)}
 const selected=[hubTerminals[0]];while(selected.length<6){let best=-1,chosen=hubTerminals[0];for(let j=0;j<hubTerminals.length;j++){const id=hubTerminals[j];if(selected.includes(id))continue;let nearest=Infinity;for(let k=0;k<selected.length;k++)nearest=Math.min(nearest,nodes[id].p.distanceToSquared(nodes[selected[k]].p));if(nearest>best){best=nearest;chosen=id}}selected.push(chosen)}
 const group=new THREE.Group();g.root.add(group);const primaryNodes=new Set(),curves=[],anchors=[],worldAnchors=[],paths=[],pathRadii=[];
 for(let i=0;i<6;i++){let id=selected[i],path=[],radii=[];while(id>=0){path.unshift(nodes[id].p.clone());radii.unshift(nodes[id].r);primaryNodes.add(id);id=nodes[id].parent}paths.push(path);pathRadii.push(radii);curves.push(new THREE.CatmullRomCurve3(path,false,'centripetal'));anchors.push(path[path.length-1]);}
 g.root.rotation.set(.16,.72,0);g.root.updateMatrixWorld(true);for(let i=0;i<6;i++)worldAnchors.push(g.root.localToWorld(anchors[i].clone()));
 const vertices=[],indices=[],branch=[],pathAttr=[],starts=[],ends=[];const scratch=new V(),tangent=new V(),side=new V(),up=new V(),axis=new V(0,1,0);
 function tube(curve,id,start,end,radius){const rings=Math.max(12,Math.ceil(curve.getLength()/.03)),offset=vertices.length/3;for(let j=0;j<=rings;j++){const f=j/rings;curve.getPointAt(f,scratch);curve.getTangentAt(f,tangent);side.crossVectors(tangent,Math.abs(tangent.y)>.95?new V(1,0,0):axis).normalize();up.crossVectors(side,tangent).normalize();const u=curve.getUtoTmapping(f),rs=id<=6?pathRadii[id-1]:null,ri=rs?u*(rs.length-1):0,lo=Math.floor(ri),r=rs?Math.max(.004,PB.mix(rs[lo],rs[Math.min(lo+1,rs.length-1)],ri-lo))*.85:radius*(1-.75*f)  /* PORT: slightly thicker stems */;for(let k=0;k<5;k++){const a=k/5*Math.PI*2;vertices.push(scratch.x+r*(Math.cos(a)*side.x+Math.sin(a)*up.x),scratch.y+r*(Math.cos(a)*side.y+Math.sin(a)*up.y),scratch.z+r*(Math.cos(a)*side.z+Math.sin(a)*up.z));branch.push(id);pathAttr.push(f);starts.push(start);ends.push(end);if(j<rings){const v=offset+j*5+k,n=offset+j*5+(k+1)%5;indices.push(v,n,v+5,n,n+5,v+5)}}}}
 for(let i=0;i<6;i++)tube(curves[i],i+1,i===0?.30:.38+i/6*.5,i===0?.38:.38+i/6*.5+.0333,.024);
 // Three explicit semantic tips originate together at the engine terminal.
 const fork=anchors[2],tips=[fork.clone().add(new V(-.3,.30,.05)),fork.clone().add(new V(0,.45,-.05)),fork.clone().add(new V(.34,.26,.05))];
 for(let i=0;i<3;i++){const c=new THREE.CatmullRomCurve3([fork,fork.clone().lerp(tips[i],.5).add(new V(0,.09,0)),tips[i]]);tube(c,8+i,.55,.58,.015)}
 const uniforms={uLeafColors:{value:[new THREE.Color(0x72e6a1),new THREE.Color(0xf1c34f),new THREE.Color(0xff6f72)]},uProgress:{value:0},uTime:{value:0},uHover:{value:-1},uReduced:{value:PB.reduced?1:0}};
 const vertex='attribute float aPath,aStart,aEnd,aBranch; uniform float uProgress,uReduced; varying float vPath,vLocal,vBranch; void main(){vPath=aPath;vBranch=aBranch;vLocal=mix(clamp((uProgress-aStart)/max(.0001,aEnd-aStart),0.,1.),1.,uReduced);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}';
 const fragment='uniform vec3 uLeafColors[3];uniform float uTime,uHover; varying float vPath,vLocal,vBranch; void main(){if(vPath>vLocal)discard;vec3 col=mix(vec3(.50,.60,.38),vec3(.86,.90,.74),vPath);if(vBranch>7.5&&vBranch<8.5)col=uLeafColors[0];if(vBranch>8.5&&vBranch<9.5)col=uLeafColors[1]*(.78+.22*sin(uTime*8.796));if(vBranch>9.5)col=uLeafColors[2]*(.9+.1*sin(uTime*3.14159));float tip=(1.-smoothstep(0.,.05,vLocal-vPath))*step(vLocal,.999);float pulse=.62+.12*sin(uTime*2.-vPath*18.);float hover=abs(vBranch-uHover)<.1?1.4:1.;float cap=(vBranch>6.5&&vBranch<7.5)?0.34:0.8 /* PORT: visible capillaries */;gl_FragColor=vec4(col*(pulse+tip*.4)*hover,cap);}';
 function geometry(positions,b,p,s,e){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('aBranch',new THREE.Float32BufferAttribute(b,1));geo.setAttribute('aPath',new THREE.Float32BufferAttribute(p,1));geo.setAttribute('aStart',new THREE.Float32BufferAttribute(s,1));geo.setAttribute('aEnd',new THREE.Float32BufferAttribute(e,1));return geo}
 const mat=new THREE.ShaderMaterial({uniforms,vertexShader:vertex,fragmentShader:fragment,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide});
 const primaryGeo=geometry(vertices,branch,pathAttr,starts,ends);primaryGeo.setIndex(indices);group.add(new THREE.Mesh(primaryGeo,mat));
 const cp=[],cb=[],ca=[],cs=[],ce=[];for(let i=1;i<nodes.length;i++){if(primaryNodes.has(i))continue;const n=nodes[i],a=nodes[n.parent].p,b=n.p;cp.push(a.x,a.y,a.z,b.x,b.y,b.z);cb.push(7,7);ca.push(nodes[n.parent].depth/45,n.depth/45);cs.push(.4,.4);ce.push(.9,.9)}const capGeo=geometry(cp,cb,ca,cs,ce);const cap=new THREE.LineSegments(capGeo,mat);group.add(cap);
 // Apply-ring convergence lines are faint until the final canopy shot.
 const gatePoint=new V(0,2.05,0),converge=[];for(let i=0;i<6;i++)converge.push(anchors[i].x,anchors[i].y,anchors[i].z,gatePoint.x,gatePoint.y,gatePoint.z);
 const convergeMat=new THREE.LineBasicMaterial({color:0xb6c09b,transparent:true,opacity:0,depthWrite:false});group.add(new THREE.LineSegments(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(converge,3)),convergeMat));
 const ringGeo=new THREE.BufferGeometry().setFromPoints(new THREE.EllipseCurve(0,0,.23,.23,0,Math.PI*2).getPoints(64)),gateMat=new THREE.LineBasicMaterial({color:0xff6f72,transparent:true,opacity:0});const gate=new THREE.LineLoop(ringGeo,gateMat);gate.position.copy(gatePoint);group.add(gate);
 const denyRing=new THREE.LineLoop(ringGeo.clone(),new THREE.LineBasicMaterial({color:0xff6f72,transparent:true,opacity:.8}));denyRing.scale.setScalar(.4);denyRing.position.copy(tips[2]);group.add(denyRing);
 const lock=new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints([new V(-.10,-.08,0),new V(.10,-.08,0),new V(.1,-.08,0),new V(.1,.06,0),new V(.1,.06,0),new V(-.1,.06,0),new V(-.1,.06,0),new V(-.1,-.08,0),new V(-.06,.06,0),new V(-.06,.15,0),new V(-.06,.15,0),new V(.06,.15,0),new V(.06,.15,0),new V(.06,.06,0)]),gateMat);lock.position.copy(gatePoint);group.add(lock);
 const packetArray=new Float32Array(150*3),packetPhase=new Float32Array(150);for(let i=0;i<150;i++)packetPhase[i]=random();const packetGeo=new THREE.BufferGeometry().setAttribute('position',new THREE.BufferAttribute(packetArray,3));const packets=new THREE.Points(packetGeo,new THREE.PointsMaterial({color:0xe4ead5,size:.022,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));group.add(packets);
 const railPoints=[new V(.53,-.18,-1.2)],lookPoints=[new V(1.93,.05,-2.7)];for(let i=0;i<6;i++){railPoints.push(worldAnchors[i].clone().add(new V(-.35,.18,PB.width<700?3.5:2.8)));lookPoints.push(worldAnchors[i].clone().add(new V(.25,0,0)))}railPoints.push(new V(2.05,.5,7.5));lookPoints.push(new V(2.05,.5,0));
 const railCurve=new THREE.CatmullRomCurve3(railPoints,false,'centripetal'),lookCurve=new THREE.CatmullRomCurve3(lookPoints,false,'centripetal');railCurve.arcLengthDivisions=1400;lookCurve.arcLengthDivisions=1400;const lengths=railCurve.getLengths(1400),lookLengths=lookCurve.getLengths(1400),stations=[];
 const sticky=document.querySelector('.hero-sticky'),svg=document.querySelector('.leaders'),rail=document.querySelector('.station-rail'),cards=[],leaders=[],ticks=[];
 for(let i=0;i<6;i++){const f=PB.FEATURES[i];stations.push({t:lengths[(i+1)*200]/lengths[1400],lookT:lookLengths[(i+1)*200]/lookLengths[1400]});const card=document.createElement('article');card.className='node';card.dataset.cursor='OPEN';card.innerHTML='<div class="caption">STATION '+f.n+' / 06</div><div class="stepper"><span>Intent confirmed</span><span>Plan evaluated</span><span>Human resolved</span></div><h3>'+f.title+'</h3><p>'+f.body+'</p>'+(i===2?'<div class="chips"><span tabindex="0" data-verdict="allow">ALLOW · inside the contract</span><span tabindex="0" data-verdict="review">REVIEW · a human decides</span><span tabindex="0" data-verdict="deny">DENY · policy prohibits</span></div>':'')+'<div class="metric">'+f.metric+'</div><button class="open" data-cursor="OPEN">Open evidence ↗</button>';card.querySelector('button').addEventListener('click',()=>PB.open(i));card.querySelectorAll('[data-verdict]').forEach(el=>{el.addEventListener('pointerenter',()=>PB.bus.emit('verdict',el.dataset.verdict));el.addEventListener('focus',()=>PB.bus.emit('verdict',el.dataset.verdict))});sticky.appendChild(card);cards.push({el:card,x:-999,y:-999});const line=document.createElementNS('http://www.w3.org/2000/svg','line');svg.appendChild(line);leaders.push(line);const tick=document.createElement('button');tick.textContent=f.n;tick.setAttribute('aria-label','Go to '+f.title);tick.addEventListener('click',()=>PB.go(.38+(i+.7)/6*.5));rail.appendChild(tick);ticks.push(tick)}
 const hud=document.querySelector('.tree-hud'),hudNumber=document.getElementById('station-number'),hudTitle=document.getElementById('station-title'),live=document.getElementById('station-live'),projected=new V(),railScratch=new V(),lookScratch=new V();
 let active=-1;const proxies=[],ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),hits=[];for(let i=0;i<6;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.12,8,6),new THREE.MeshBasicMaterial({visible:false}));m.position.copy(anchors[i]);m.userData.station=i;group.add(m);proxies.push(m)}
 let hovered=-1;PB.listen(document.getElementById('globe-canvas'),'click',()=>{if(hovered>=0)PB.open(hovered)});
 function stationParam(p,field){const s=PB.clamp((p-.38)/.5),k=Math.min(5,Math.floor(s*6)),local=s*6-k,travel=PB.smooth(local/.4),t0=k===0?0:stations[k-1][field];return PB.mix(t0,stations[k][field],travel)}
 PB.tree={gate,gateMat,lock,ringGeo,uniforms,denyRing,nodes,selected,stations,railCurve,lookCurve,group,segments:nodes.length-1,railT:p=>stationParam(p,'t'),update(dt,t,p,baseLook){
  uniforms.uProgress.value=p;uniforms.uTime.value=PB.reduced?0:t;group.visible=p>=.30||PB.reduced;
  if(p>.30&&p<.38){const f=(p-.30)/.08;g.camera.position.x+=Math.sin(f*Math.PI)*.15;g.camera.lookAt(baseLook)}
  if(p>=.38){let rt=stationParam(p,'t'),lt=stationParam(p,'lookT');if(p>.88){const f=PB.smooth((p-.88)/.08);rt=PB.mix(stations[5].t,1,f);lt=PB.mix(stations[5].lookT,1,f)}railCurve.getPointAt(rt,railScratch);lookCurve.getPointAt(lt,lookScratch);g.camera.position.copy(railScratch);g.camera.lookAt(lookScratch)}
  g.camera.updateMatrixWorld(true);group.updateMatrixWorld(true);
  const stationPhase=p>=.38&&p<.88,k=stationPhase?Math.min(5,Math.floor((p-.38)/.5*6)):-1,local=stationPhase?((p-.38)/.5*6-k):0,next=local>=.4?k:-1;
  hud.style.opacity=p>.31&&p<.96?'1':'0';rail.classList.toggle('visible',p>.32&&p<.96);
  if(next!==active){active=next;for(let i=0;i<6;i++){cards[i].el.classList.toggle('active',i===active);cards[i].el.inert=i!==active;ticks[i].setAttribute('aria-current',String(i===active));leaders[i].style.display=i===active?'':'none'}if(active>=0){hudNumber.textContent=PB.FEATURES[active].n+' / 06';hudTitle.textContent=PB.FEATURES[active].kicker;live.textContent=PB.FEATURES[active].title;PB.audio&&PB.audio.tick()}}
  if(p>=.88){hudNumber.textContent='BOUNDARY / CLOSED';hudTitle.textContent='One path. A firm boundary.'}else if(p<.38){hudNumber.textContent='ROOT / 00';hudTitle.textContent='Intent takes shape.'}
  if(active>=0){projected.copy(anchors[active]);g.root.localToWorld(projected);projected.project(g.camera);const ax=(projected.x*.5+.5)*PB.width,ay=(-projected.y*.5+.5)*PB.height,card=cards[active],x=PB.width<700?20:PB.clamp(ax+70,PB.width*.42,PB.width-410),y=PB.width<700?PB.height*.44:PB.clamp(ay-120,PB.height*.30,PB.height-380);if(Math.abs(x-card.x)>.5||Math.abs(y-card.y)>.5){card.el.style.transform='translate3d('+x+'px,'+y+'px,0)';card.x=x;card.y=y}const line=leaders[active];line.setAttribute('x1',ax);line.setAttribute('y1',ay);line.setAttribute('x2',x);line.setAttribute('y2',y+80)}
  packets.visible=!PB.reduced&&PB.quality<5&&p>.38; if(packets.visible){for(let i=0;i<150;i++){const b=i%6,start=b===0?.30:.38+b/6*.5,amount=PB.clamp((p-start)/.0333);packetPhase[i]=(packetPhase[i]+dt*(hovered===b?.16:.08))%1;curves[b].getPointAt(Math.min(packetPhase[i],amount),scratch);packetArray[i*3]=scratch.x;packetArray[i*3+1]=scratch.y;packetArray[i*3+2]=scratch.z}packetGeo.attributes.position.needsUpdate=true}
  if(PB.quality>=3)capGeo.setDrawRange(0,Math.floor(cp.length/12)*2);denyRing.visible=p>.58;const closure=PB.smooth((p-.88)/.08);gateMat.opacity=closure;convergeMat.opacity=closure*.35;ringGeo.setDrawRange(0,Math.max(2,Math.floor(65*closure)));gate.rotation.z=(1-closure)*Math.PI;lock.visible=closure>.8;
  pointer.set(PB.pointer.ndcX,PB.pointer.ndcY);ray.setFromCamera(pointer,g.camera);hits.length=0;ray.intersectObjects(proxies,false,hits);hovered=hits.length?hits[0].object.userData.station:-1;uniforms.uHover.value=hovered+1;if(hovered>=0&&PB.cursor)PB.cursor.label('OPEN');
 }};
 // Exact rail handoff test compares both numeric position and look target.
 PB.checkContinuity=function(){const original=g.originalPose(1),start=railCurve.getPointAt(0),look=lookCurve.getPointAt(0);return {positionError:start.distanceTo(new V(...original.position)),lookError:look.distanceTo(new V(...original.look)),original,railStart:start.toArray(),railLook:look.toArray()}};
 PB.boot.complete('tree','Grew '+(nodes.length-1)+' decision segments · seed 0x5EED');
 g.renderer.compile(g.scene,g.camera);PB.boot.complete('shaders','Hero and tree shader compilation requested');PB.activeScope=null;PB.bus.emit('tree-ready',PB.tree);
}
requestAnimationFrame(chunk);
})();


};
}
