"""One-time port of the ORIGINAL PlanBound engine into web/src/planbound/engine.

Reads design/planbound-site.html (left untouched) and writes each running
script as an ES module whose body is the original code, unchanged, except for
the small disposal hooks React needs (marked `// PORT:`).
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
html = (ROOT / "design/planbound-site.html").read_text(encoding="utf-8")
scripts = [re.sub(r"^<script[^>]*>|</script>$", "", m.group(0)) for m in re.finditer(r"<script[^>]*>.*?</script>", html, re.S)]
OUT = ROOT / "web/src/planbound/engine"
OUT.mkdir(parents=True, exist_ok=True)

MODULES = {0: "core", 1: "boot", 2: "support", 10: "hero", 11: "tree", 12: "robot", 13: "audio", 14: "cursor", 15: "perf"}

def patch(name, code):
    if name == "core":
        code = code.replace("function tick(now){raf=0;if(document.hidden)return;", "function tick(now){raf=0;if(PB.disposed||document.hidden)return; // PORT: stop after dispose\n")
        code = code.replace("PB.wake=function(){if(!raf&&!document.hidden)raf=requestAnimationFrame(tick)}", "PB.wake=function(){if(!raf&&!document.hidden&&!PB.disposed)raf=requestAnimationFrame(tick)} // PORT: stop after dispose")
        assert "PB.disposed" in code
    return code

for idx, name in MODULES.items():
    body = patch(name, scripts[idx].strip("\n"))
    text = (
        f"// GENERATED by tools/port_planbound_engine.py from design/planbound-site.html (script #{idx}).\n"
        "// The body below is the original running code. Do not hand-edit; re-run the generator.\n"
        "/* eslint-disable */\n"
        f"export default function install{name.capitalize()}(THREE) {{\n{body}\n}}\n"
    )
    (OUT / f"{name}.js").write_text(text, encoding="utf-8")
    print(name, len(text))

css = "\n".join(m.group(1) for m in re.finditer(r"<style[^>]*>(.*?)</style>", html, re.S))
(ROOT / "web/src/planbound/planbound.css").write_text("/* Verbatim from design/planbound-site.html <style>. */\n" + css, encoding="utf-8")

body = html[html.index("<body"):]
body = re.sub(r"<script.*?</script>", "", body, flags=re.S)
def between(a, b):
    i = body.index(a); j = body.index(b, i); return body[i + len(a): j]
shell_top = body[body.index('<div id="boot"'): body.index('<nav class="site-nav">')]
home = between('<main id="view" tabindex="-1"><div id="home-view">', '</div><div id="route-view" hidden></div></main>')
(ROOT / "web/src/planbound/shell.generated.js").write_text(
    "// GENERATED by tools/port_planbound_engine.py: original markup, verbatim.\n"
    f"export const SHELL_HTML = {json.dumps(shell_top)};\n"
    f"export const HOME_HTML = {json.dumps(home)};\n", encoding="utf-8")
print("home", len(home), "shell", len(shell_top))
