(function(){
'use strict';const PB=window.PB;if(!PB.webgl||typeof THREE==='undefined')return;
const canvas=document.getElementById('robot-canvas'),section=document.getElementById('unit'),status=document.getElementById('robot-status'),word=document.getElementById('studio-word');
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true})}catch(e){PB.boot.complete('robot','Reviewer unavailable — text fallback ready');return}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.01,50);camera.position.set(0,.2,4.1);camera.lookAt(0,-.03,0);
scene.add(new THREE.HemisphereLight(0xe8edf5,0x77716d,.45));const key=new THREE.DirectionalLight(0xfff5e6,1.2);key.position.set(-3,5,4);scene.add(key);const fill=new THREE.DirectionalLight(0x9dc4ef,.55);fill.position.set(3,1,1);scene.add(fill);
const envScene=new THREE.Scene();envScene.background=new THREE.Color(0x555a60);for(let i=0;i<3;i++){const mesh=new THREE.Mesh(new THREE.PlaneGeometry(3,5),new THREE.MeshBasicMaterial({color:i===1?0xb9cde0:0xffffff}));mesh.position.set(i===0?-4:i===1?4:0,i===2?5:2,i===2?-2:2);mesh.lookAt(0,0,0);envScene.add(mesh)}const pmrem=new THREE.PMREMGenerator(renderer),environment=pmrem.fromScene(envScene,.04);scene.environment=environment.texture;pmrem.dispose();envScene.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose()});
const bust=new THREE.Group(),neckPivot=new THREE.Group(),headPivot=new THREE.Group();scene.add(bust);bust.add(neckPivot);neckPivot.position.y=-.25;neckPivot.add(headPivot);headPivot.position.y=.48;
const metal=new THREE.MeshStandardMaterial({color:0x7c8087,metalness:.35,roughness:.45,envMapIntensity:.5}),black=new THREE.MeshStandardMaterial({color:0x080809,roughness:.6,envMapIntensity:.25}),rubber=new THREE.MeshStandardMaterial({color:0x030304,roughness:.88,envMapIntensity:.15});
function rounded(w,h,r){const s=new THREE.Shape(),x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s}
function shell(w,h,r,depth,material,z){const m=new THREE.Mesh(new THREE.ExtrudeGeometry(rounded(w,h,r),{depth,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.025,bevelThickness:.025,curveSegments:12}),material);m.position.z=z;headPivot.add(m);return m}
shell(1,.94,.08,.62,metal,-.43);shell(.94,.87,.065,.08,black,.19);shell(.85,.73,.05,.035,rubber,.29);
const screenCanvas=document.createElement('canvas');screenCanvas.width=512;screenCanvas.height=448;const context=screenCanvas.getContext('2d'),texture=new THREE.CanvasTexture(screenCanvas);texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;texture.generateMipmaps=false;
const uniforms={uTex:{value:texture},uTime:{value:0},uBoot:{value:0},uGlitch:{value:0},uRes:{value:new THREE.Vector2(512,448)},uLook:{value:new THREE.Vector2()}};
const crt=new THREE.ShaderMaterial({uniforms,vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform sampler2D uTex;uniform float uTime,uBoot,uGlitch;uniform vec2 uRes,uLook;varying vec2 vUv;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){vec2 c=(vUv+uLook*.02)*2.-1.;c*=1.+.1*dot(c,c);vec2 uv=c*.5+.5;if(uv.x<0.||uv.x>1.||uv.y<0.||uv.y>1.){gl_FragColor=vec4(0.,0.,0.,1.);return;}float ca=.0015+.01*uGlitch;vec3 col=vec3(texture2D(uTex,uv+vec2(ca,0.)).r,texture2D(uTex,uv).g,texture2D(uTex,uv-vec2(ca,0.)).b);col*=.86+.14*sin(uv.y*uRes.y*3.14159);col*=.93+.07*sin(uv.x*uRes.x*6.28318);col+=(hash(uv*uRes+uTime)-.5)*.035;col*=1.-smoothstep(.35,.95,length(vUv-.5)*1.25);float opening=clamp(uBoot,0.,1.),band=abs(vUv.y-.5)*2.;col*=step(band,opening*opening+.004);col+=(1.-opening)*vec3(.9)*step(band,.006);gl_FragColor=vec4(col,1.);}' });
const screenGeo=new THREE.PlaneGeometry(.78,.70,48,48),vertices=screenGeo.attributes.position;for(let i=0;i<vertices.count;i++){const x=vertices.getX(i),y=vertices.getY(i);vertices.setZ(i,.035*(1-(x*x+y*y)*3.1))}screenGeo.computeVertexNormals();const screen=new THREE.Mesh(screenGeo,crt);screen.position.set(0,.025,.345);headPivot.add(screen);
const glass=new THREE.Mesh(screenGeo.clone(),new THREE.MeshPhysicalMaterial({color:0xcfd7dd,transparent:true,opacity:.065,roughness:.05,clearcoat:1,clearcoatRoughness:.05,depthWrite:false}));glass.position.copy(screen.position);glass.position.z+=.007;headPivot.add(glass);
function mesh(geo,mat,parent,x,y,z){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);parent.add(m);return m}
const ledMat=new THREE.MeshBasicMaterial({color:0x5b7cff});const led=mesh(new THREE.SphereGeometry(.011,12,8),ledMat,headPivot,.13,-.383,.365);led.scale.set(1.6,.65,.5);
for(let i=0;i<5;i++){const pill=mesh(new THREE.SphereGeometry(.008,10,6),metal,headPivot,.19+i*.04,-.384,.365);pill.scale.set(1.7,.7,.45)}
for(const side of [-1,1]){const ear=mesh(new THREE.CylinderGeometry(.13,.13,.07,32),rubber,headPivot,side*.54,-.1,-.04);ear.rotation.z=Math.PI/2;mesh(new THREE.BoxGeometry(.04,.15,.12),metal,headPivot,side*.49,-.10,-.08)}
mesh(new THREE.BoxGeometry(.40,.045,.24),metal,headPivot,0,-.515,-.01);for(const side of [-1,1]){const hex=mesh(new THREE.CylinderGeometry(.031,.031,.06,6),metal,headPivot,side*.15,-.53,.05);hex.rotation.x=Math.PI/2}for(let i=0;i<3;i++)mesh(new THREE.CylinderGeometry(.014,.014,.085,12),rubber,headPivot,(i-1)*.09,-.56,.1);
mesh(new THREE.CylinderGeometry(.17,.19,.30,32),new THREE.MeshStandardMaterial({color:0xc9a58f,roughness:.7}),neckPivot,0,0,0);
const knitCanvas=document.createElement('canvas');knitCanvas.width=knitCanvas.height=512;const kc=knitCanvas.getContext('2d'),image=kc.createImageData(512,512),rng=PB.rng(172);for(let y=0;y<512;y++)for(let x=0;x<512;x++){const value=128+48*Math.sin(x/512*Math.PI*128)+16*Math.sin(y*.7+x*.06)+(rng()-.5)*20,q=(y*512+x)*4;image.data[q]=image.data[q+1]=image.data[q+2]=value;image.data[q+3]=255}kc.putImageData(image,0,0);const knitTex=new THREE.CanvasTexture(knitCanvas);knitTex.wrapS=knitTex.wrapT=THREE.RepeatWrapping;knitTex.repeat.set(3,2);
const knit=new THREE.MeshPhysicalMaterial({color:0x726069,roughness:.95,bumpMap:knitTex,bumpScale:.015,sheen:new THREE.Color(0x302b2d)});
const profile=[new THREE.Vector2(0,-1.2),new THREE.Vector2(.34,-1.2),new THREE.Vector2(.44,-1.1),new THREE.Vector2(.49,-.86),new THREE.Vector2(.46,-.67),new THREE.Vector2(.39,-.54),new THREE.Vector2(.28,-.44),new THREE.Vector2(.19,-.35),new THREE.Vector2(.17,-.12),new THREE.Vector2(.155,-.10),new THREE.Vector2(.15,-.32)];
const softProfile=new THREE.SplineCurve(profile).getPoints(100);const torso=mesh(new THREE.LatheGeometry(softProfile,64),knit,bust,0,0,-.03);torso.scale.set(1.8,1,.8);const collar=mesh(new THREE.TorusGeometry(.17,.03,12,40),knit,bust,0,-.15,-.03);collar.rotation.x=Math.PI/2;
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=128;const sx=shadowCanvas.getContext('2d'),gradient=sx.createRadialGradient(64,64,0,64,64,64);gradient.addColorStop(0,'rgba(0,0,0,.24)');gradient.addColorStop(1,'rgba(0,0,0,0)');sx.fillStyle=gradient;sx.fillRect(0,0,128,128);const shadow=mesh(new THREE.PlaneGeometry(2.8,1.1),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}),scene,0,-1.23,0);shadow.rotation.x=-Math.PI/2;
// Seven fixed-topology cable tubes; Verlet nodes and transport frames are reused.
const cables=[],anchorScratch=new THREE.Vector3(),direction=new THREE.Vector3(),sideScratch=new THREE.Vector3(),upScratch=new THREE.Vector3(),worldUp=new THREE.Vector3(0,0,1);
for(let strand=0;strand<7;strand++){const anchor=new THREE.Vector3(strand<3?(strand-1)*.09:strand<5?-.56:.56,strand<3?-.59:-.10,strand<3?.10:-.04);const points=new Float32Array(54),previous=new Float32Array(54),tubePos=new Float32Array(18*5*3),idx=[];for(let j=0;j<18;j++){points[j*3]=anchor.x+Math.sin(j/17*Math.PI*2+strand)*.09;points[j*3+1]=anchor.y+.23-j*.045;points[j*3+2]=.25+Math.sin(j/17*Math.PI)*.18;for(let r=0;r<5;r++)if(j<17){const a=j*5+r,b=j*5+(r+1)%5;idx.push(a,b,a+5,b,b+5,a+5)}}previous.set(points);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(tubePos,3));geo.setIndex(idx);const cable=new THREE.Mesh(geo,rubber);cable.frustumCulled=false;scene.add(cable);cables.push({anchor,points,previous,geo,tubePos})}
const yaw={x:0,v:0},pitch={x:0,v:0},roll={x:-.052,v:0},ny={x:0,v:0},np={x:0,v:0},ty={x:0,v:0},lx={x:0,v:0},ly={x:0,v:0},boot={x:0,v:0},headCentre=new THREE.Vector3();
let entered=0,accumulator=0,lastTex=-1,curiousUntil=0,ackUntil=0,verdictUntil=0,verdict='',lastState='',wordIndex=-1,blinkNext=5,blinkUntil=0;
const stars=[];for(let i=0;i<100;i++)stars.push([rng()*512,rng()*448,rng()]);const lines=['PLANBOUND / PB-01','authorization: confirmed','plan.hash: 5e6b4e5a','iam.ec2_role      ALLOW','sg.web_sg        REVIEW','s3.assets         DENY','apply.spawned: false','gate: CLOSED'];
PB.robot={renderer,scene,camera,headPivot,cables,visible:false,state:'BOOT',headAngVel:0};PB.observe(section,PB.robot);
function resize(){renderer.setSize(PB.width,PB.height,false);camera.aspect=PB.width/PB.height;camera.position.z=PB.width<700?5.4:4.1;camera.updateProjectionMatrix()}resize();PB.bus.on('resize',resize);
function acknowledge(){ackUntil=performance.now()/1000+.7;for(let i=0;i<cables.length;i++)for(let j=3;j<54;j++)cables[i].previous[j]+=(rng()-.5)*.15;PB.audio.click()}
section.addEventListener('pointerdown',acknowledge);document.getElementById('studio-ack').addEventListener('click',e=>{if(e.detail===0)acknowledge()});
PB.bus.on('verdict',v=>{verdict=v;verdictUntil=performance.now()/1000+4});
function cableStep(dt){headPivot.updateWorldMatrix(true,false);for(let c=0;c<7;c++){const cable=cables[c],p=cable.points,prev=cable.previous;anchorScratch.copy(cable.anchor);headPivot.localToWorld(anchorScratch);p[0]=anchorScratch.x;p[1]=anchorScratch.y;p[2]=anchorScratch.z;for(let j=1;j<18;j++){const q=j*3;for(let d=0;d<3;d++){const value=p[q+d];p[q+d]+=(value-prev[q+d])*.985;prev[q+d]=value}p[q+1]-=2.45*dt*dt;if(j<6)p[q]+=yaw.v*.000015}
 for(let it=0;it<6;it++){for(let j=1;j<18;j++){const a=(j-1)*3,b=j*3,dx=p[b]-p[a],dy=p[b+1]-p[a+1],dz=p[b+2]-p[a+2],length=Math.max(.0001,Math.hypot(dx,dy,dz)),f=(length-.06)/length*(j===1?1:.5);if(j>1){p[a]+=dx*f;p[a+1]+=dy*f;p[a+2]+=dz*f}p[b]-=dx*f;p[b+1]-=dy*f;p[b+2]-=dz*f;
 const ex=p[b]/.86,ey=(p[b+1]+.82)/.43,ez=(p[b+2]+.03)/.4,l=Math.sqrt(ex*ex+ey*ey+ez*ez);if(l<1&&l>.001){p[b]=ex/l*.86;p[b+1]=ey/l*.43-.82;p[b+2]=ez/l*.4-.03}if(p[b+1]>-.4&&p[b+1]<.0){const l=Math.hypot(p[b],p[b+2]);if(l<.2&&l>.001){p[b]*=.2/l;p[b+2]*=.2/l}}}p[0]=anchorScratch.x;p[1]=anchorScratch.y;p[2]=anchorScratch.z}
 }}
function drawCable(cable){const p=cable.points,a=cable.tubePos;sideScratch.set(1,0,0);for(let j=0;j<18;j++){const q=j*3,prev=Math.max(0,j-1)*3,next=Math.min(17,j+1)*3;direction.set(p[next]-p[prev],p[next+1]-p[prev+1],p[next+2]-p[prev+2]).normalize();sideScratch.addScaledVector(direction,-sideScratch.dot(direction));if(sideScratch.lengthSq()<.0001)sideScratch.crossVectors(direction,worldUp);sideScratch.normalize();upScratch.crossVectors(direction,sideScratch).normalize();for(let k=0;k<5;k++){const angle=k/5*Math.PI*2,co=Math.cos(angle)*.006,si=Math.sin(angle)*.006,v=(j*5+k)*3;a[v]=p[q]+sideScratch.x*co+upScratch.x*si;a[v+1]=p[q+1]+sideScratch.y*co+upScratch.y*si;a[v+2]=p[q+2]+sideScratch.z*co+upScratch.z*si}}cable.geo.attributes.position.needsUpdate=true;cable.geo.computeVertexNormals()}
function screenContent(state,t,dx,dy){context.fillStyle='#080b0b';context.fillRect(0,0,512,448);for(let i=0;i<stars.length;i++){context.fillStyle='rgba(222,231,221,'+(.12+stars[i][2]*.4)+')';context.fillRect(stars[i][0],stars[i][1],1,1)}context.font='10px monospace';context.textAlign='left';for(let i=0;i<lines.length;i++){context.fillStyle=i>2?'#6d9277':'#69816c';context.fillText(lines[i],45,42+i*13)}context.fillStyle='#a9b3ef';context.font='bold 16px monospace';context.fillText('PB-01',382,38);context.textAlign='center';let glyph=state==='ACK'?'ACK':state==='CURIOUS'?'?':state==='IDLE'?'BOUNDARY / ONLINE':'+';context.fillStyle='#c6cce9';if(verdictUntil>t){glyph=verdict.toUpperCase();context.fillStyle=verdict==='allow'?'#72e6a1':verdict==='review'?'#f1c34f':'#ff6f72'}context.font=(glyph==='+'?'48':'24')+'px monospace';context.fillText(glyph,256+(state==='TRACK'?dx*45:0),292+(state==='TRACK'?dy*35:0));context.font='10px monospace';context.fillStyle='#71806e';context.fillText('THE AGENT PROPOSES. THE BOUNDARY DECIDES.',256,394);if(state==='ACK'&&ackUntil-t>.62){context.fillStyle='rgba(220,228,247,.75)';context.fillRect(0,0,512,448)}if(t<blinkUntil){context.fillStyle='rgba(0,0,0,.85)';context.fillRect(0,0,512,448)}texture.needsUpdate=true}
PB.frame((dt,t)=>{if(!PB.robot.visible||!PB.started)return;if(!entered){entered=t;PB.audio.tone(75,.3,.055,30)}if(t>blinkNext){blinkUntil=t+.12;blinkNext=t+4+rng()*3}
 headPivot.getWorldPosition(headCentre);headCentre.project(camera);const hx=(headCentre.x*.5+.5)*PB.width,hy=(-headCentre.y*.5+.5)*PB.height,dx=(PB.pointer.x-hx)/PB.height,dy=(PB.pointer.y-hy)/PB.height,idle=PB.touch||!PB.pointer.inside||t*1000-PB.pointer.time>2500;
 if(PB.pointer.speed>2500&&!PB.reduced)curiousUntil=t+.6;const state=PB.reduced?'IDLE':t-entered<.9?'BOOT':ackUntil>t?'ACK':curiousUntil>t?'CURIOUS':idle?'IDLE':'TRACK';PB.robot.state=state;if(state!==lastState){status.textContent=state;lastState=state}
 let targetY=idle?Math.sin(t*.31)*.35+Math.sin(t*.71)*.12:PB.clamp(Math.atan2(dx*2.2,1.4),-.663,.663),targetP=idle?Math.sin(t*.23)*.12:PB.clamp(-Math.atan2(dy*2.2,1.4),-.384,.384);targetP+=PB.clamp(PB.scrollVel*.000015,-.104,.104);if(PB.reduced){targetY=0;targetP=0}
 const zeta=PB.reduced?1:state==='CURIOUS'?.35:.55;PB.spring(yaw,targetY,9,zeta,dt);PB.spring(pitch,targetP,9,zeta,dt);PB.spring(roll,-.052-targetY*.18+(PB.reduced?0:Math.sin(t*.8)*.008),9,zeta,dt);PB.spring(ny,targetY*.45,5,.8,dt);PB.spring(np,targetP*.45,5,.8,dt);PB.spring(ty,targetY*.2,3.2,.9,dt);PB.spring(lx,PB.reduced?0:dx*.05,4,1,dt);PB.spring(ly,PB.reduced?0:-dy*.03,4,1,dt);headPivot.rotation.set(pitch.x,yaw.x,roll.x);headPivot.position.set(lx.x,.48+ly.x,0);neckPivot.rotation.set(np.x,ny.x,0);bust.rotation.y=ty.x;PB.robot.headAngVel=yaw.v;
 PB.spring(boot,1,6,1,dt);uniforms.uBoot.value=PB.reduced?1:boot.x;uniforms.uTime.value=PB.reduced?0:t;uniforms.uGlitch.value=PB.reduced?0:Math.min(.35,Math.abs(yaw.v)*.035);uniforms.uLook.value.set(yaw.x,pitch.x);ledMat.color.setHex(state==='ACK'?0xffffff:0x5b7cff);
 if(!PB.reduced||lastTex<0){accumulator=Math.min(.05,accumulator+dt);while(accumulator>=1/120){cableStep(1/120);accumulator-=1/120}for(let i=0;i<7;i++)drawCable(cables[i])}
 if(t-lastTex>=1/15&&(!PB.reduced||lastTex<0)){screenContent(state,t,dx,dy);lastTex=t}
 const next=PB.reduced?3:Math.floor((t-entered)/3)%4;if(next!==wordIndex){word.textContent=['Intent','Intent → Plan','Plan → Verdict','Verdict → Apply'][next];wordIndex=next}renderer.render(scene,camera);
});
screenContent('BOOT',0,0,0);renderer.compile(scene,camera);PB.boot.complete('robot','Calibrated reviewer PB-01 · 7 cables / 126 nodes');
})();
