(function(){
'use strict';const PB=window.PB,U=PB.ui,h=PB.h,B=U.button,L=U.link,C=U.caption;
const views=[];PB.siteViews=views;
function register(path,title,mount){views.push({path,title:'PlanBound — '+title,mount})}
const actions=(...items)=>h('div',{class:'site-actions'},items);
function attention(s){return s.changes.filter(c=>s.verdicts[c.id].verdict==='DENY'||(s.verdicts[c.id].verdict==='REVIEW'&&!PB.engine.resolution(c.id))).length}
function gateText(s){const n=attention(s),rejected=s.changes.filter(c=>PB.engine.resolution(c.id)==='rejected').length;return n?n+' of '+s.changes.length+' changes need attention before applying.':rejected?rejected+' rejected change'+(rejected>1?'s':'')+' excluded. Remaining changes are ready.':'All '+s.changes.length+' changes are within the resolved boundary.'}
PB.gateText=gateText;
function status(s){return !s.contract.confirmed?1:attention(s)?2:3}
function row(chg,index,ctx){const s=PB.store.get(),v=s.verdicts[chg.id],resolved=PB.engine.resolution(chg.id),drawer=h('div',{class:'explain-drawer',hidden:true}),el=h('article',{class:'review-row'+(resolved?' resolved-'+resolved:''),tabIndex:0,'data-change-id':chg.id});
 const explain=()=>{drawer.hidden=!drawer.hidden;if(!drawer.hidden)drawer.replaceChildren(C('MATCHED RULE / '+v.rule),h('p',{class:'rule-reason'},v.reason),U.json({rule:v.rule,contract:{hash:s.contract.hash,environment:s.contract.environment,allowed:s.contract.allowed,maxBlast:s.contract.maxBlast},change:chg,resolution:resolved}));};
 const controls=h('div',{class:'row-actions'});if(v.verdict==='REVIEW'){controls.append(B(resolved==='approved'?'Approved':'Approve',()=>PB.engine.resolve(chg.id,'approved'),{'aria-pressed':String(resolved==='approved'),'data-action':'approve'}),B(resolved==='rejected'?'Rejected · excluded':'Reject',()=>PB.engine.resolve(chg.id,'rejected'),{'aria-pressed':String(resolved==='rejected'),'data-action':'reject'}))}else if(v.verdict==='DENY')controls.append(h('span',{class:'locked'},'Locked by boundary'));
 controls.append(B(v.verdict==='ALLOW'?'View':'Explain',explain,{'data-cursor':'INSPECT','data-action':'explain'}));
 el.append(h('div',{class:'row-heading'},h('div',{},h('div',{class:'row-number'},'#'+String(index+1).padStart(2,'0')+' / '+chg.op.toUpperCase()),h('div',{class:'resource-name'},chg.resource),h('div',{class:'rule-reason'},chg.name)),U.badge(v.verdict)),U.diff(chg.before,chg.after),h('p',{class:'rule-id'},v.rule),h('p',{class:'rule-reason'},v.reason),controls,drawer);return el}

register('/contract','Contract',(el,ctx)=>{
 el.className='subview';el.append(U.heading('Define the boundary.','01 / DEFINE','Set the scope before the agent proposes a change. This browser demonstration does not authorize infrastructure.'));
 const host=h('div',{});el.append(host);let step=-1,revision=0,timer=0,alive=true;ctx.clean.push(()=>{alive=false;clearTimeout(timer)});
 function preview(){const s=PB.store.get(),json=host.querySelector('[data-contract-json]'),line=host.querySelector('[data-draft-hash]');if(json)json.replaceChildren(U.json(s.contract));if(!line)return;if(s.contract.confirmed){line.textContent='contract: '+s.contract.hash;return}const id=++revision;clearTimeout(timer);timer=setTimeout(async()=>{const digest=await PB.engine.hash(s.contract);if(alive&&id===revision)line.textContent='draft: '+digest+' / '+(crypto?.subtle?'SHA-256':'FNV-1a 64')},80)}
 function showError(message){const target=host.querySelector('[data-form-error]');target.replaceChildren(U.error(message));target.scrollIntoView({block:'nearest',behavior:PB.reduced?'instant':'smooth'})}
 function draw(force=false){const s=PB.store.get();if(!force&&step===s.wizardStep){preview();const submit=host.querySelector('[data-submit]');if(submit)submit.disabled=!s.consent;return}step=s.wizardStep;host.replaceChildren(U.stepper(step,3,['Define','Confirm','Submit']));const grid=h('div',{class:'wizard-grid'}),panel=h('div',{class:'wizard-panel'}),side=h('aside',{class:'wizard-side'},C(s.contract.confirmed?'CONFIRMED RECORD':'LIVE BOUNDARY'),h('p',{class:'hash-line','data-draft-hash':''}),h('div',{'data-contract-json':''}));grid.append(panel,side);host.append(grid);
 if(step===1){panel.append(U.toggleGroup('Environment',['dev','staging','prod'],s.contract.environment,v=>{PB.engine.draft({environment:v});draw(true)}));const resources=h('fieldset',{class:'field'},h('legend',{},'Allowed resource classes'),h('div',{class:'toggle-group'},PB.engine.classes.map(name=>B(name.replace('aws_',''),()=>{const current=PB.store.get().contract.allowed;PB.engine.draft({allowed:current.includes(name)?current.filter(x=>x!==name):[...current,name]});draw(true)},{class:'chip '+(s.contract.allowed.includes(name)?'selected':''),'aria-pressed':String(s.contract.allowed.includes(name)),'data-resource-class':name}))));
 const blast=h('input',{id:'contract-blast',type:'range',min:1,max:10,value:s.contract.maxBlast,onInput:e=>{PB.engine.draft({maxBlast:Number(e.target.value)});host.querySelector('#blast-value').textContent=e.target.value}}),note=h('textarea',{id:'contract-note',maxlength:240,value:s.contract.note,onInput:e=>{PB.engine.draft({note:e.target.value});host.querySelector('#note-count').textContent=e.target.value.length+' / 240'}});
 panel.append(resources,h('div',{class:'field'},h('label',{for:'contract-blast'},'Max blast radius · ',h('output',{id:'blast-value'},s.contract.maxBlast)),blast),h('div',{class:'field'},h('label',{for:'contract-note'},'Task note'),note,h('small',{id:'note-count'},s.contract.note.length+' / 240')),h('div',{'data-form-error':''}),actions(B('Confirm boundary →',()=>{try{PB.engine.validateContract(PB.store.get().contract);PB.store.set({wizardStep:2,consent:false})}catch(e){showError(e.message)}},{class:'site-button primary','data-cursor':'NEXT','data-next':''})));}
 else if(step===2){panel.append(C('REVIEW YOUR AUTHORIZATION'),h('p',{class:'contract-summary'},'You are authorising changes to '+s.contract.allowed.length+' resource classes in '+s.contract.environment+', with a blast-radius limit of '+s.contract.maxBlast+'.'),h('p',{class:'rule-reason'},s.contract.note||'No additional task note.'),h('label',{class:'confirm-line'},h('input',{type:'checkbox',id:'consent',checked:s.consent,onChange:e=>PB.store.set({consent:e.target.checked})}),h('span',{},'I confirm this boundary describes what the agent is allowed to change.')),h('div',{'data-form-error':''}),actions(B('← Back',()=>PB.store.set({wizardStep:1,consent:false}),{'data-cursor':'BACK'}),B('Submit confirmed boundary',async e=>{const submitted=e.currentTarget;submitted.disabled=true;try{await PB.engine.confirm();PB.toast('Boundary confirmed.')}catch(error){showError(error.message);submitted.disabled=false}},{class:'site-button primary',disabled:!s.consent,'data-submit':'','data-cursor':'NEXT'})));}
 else{panel.append(h('div',{class:'stamp'},'✓ BOUNDARY CONFIRMED / '+s.contract.hash),h('p',{class:'contract-summary'},'Intent is now explicit.'),h('p',{class:'rule-reason'},'Confirmed '+new Date(s.contract.confirmedAt).toLocaleString()+'. Editing requires a new confirmation.'),actions(B('Copy JSON',()=>U.copy(s.contract)),L('Review a plan →','/plan-review',{class:'site-button primary'}),B('Define another boundary',()=>PB.engine.reset())));}
 preview();}
 ctx.subscribe(()=>draw());draw();return()=>ctx.cleanup();
});

register('/plan-review','Plan Review',(el,ctx)=>{
 el.className='subview';el.append(U.heading('Every change. A decision.','02 / INSPECT','Inspect the matched rule, resolve uncovered changes, and test the simulated apply gate.'));
 const banner=h('div',{}),grid=h('div',{class:'review-console'}),left=h('aside',{class:'review-left'}),center=h('section',{class:'review-center','aria-label':'Plan changes'}),right=h('aside',{class:'review-right'}),contract=h('div',{class:'site-panel'}),picker=h('div',{class:'site-panel'}),companion=h('div',{class:'companion','data-robot-slot':'','data-companion':'true','data-cursor':'LOOK','aria-label':'Boundary reviewer'}),gate=h('div',{class:'site-panel gate-card'});el.append(banner,grid);grid.append(left,center,right);left.append(contract,picker);right.append(companion,gate);
 const select=h('select',{id:'sample-plan',onChange:e=>{PB.engine.load(e.target.value);PB.toast('Loaded '+e.target.value+' / SAMPLE DATA.')}});for(const [id,label]of [['sample-a','Sample A · mixed verdicts'],['sample-b','Sample B · clean plan'],['sample-c','Sample C · prod scenario']])select.append(h('option',{value:id},label));select.value=PB.store.get().planId;
 const paste=h('textarea',{id:'paste-plan','aria-label':'Paste plan JSON',spellcheck:false,placeholder:'Paste an array of normalized changes'}),pasteError=h('div',{role:'status'});picker.append(C('SAMPLE DATA / PLAN PICKER'),h('label',{for:'sample-plan'},'Choose a sample plan'),select,h('p',{class:'rule-reason'},'Sample C needs a confirmed prod boundary that includes database instances.'),L('Define a boundary →','/contract'),h('label',{for:'paste-plan'},'Paste plan JSON'),paste,B('Load pasted plan',()=>{try{if(paste.value.length>200000)throw Error('Keep pasted plans below 200 KB.');const parsed=JSON.parse(paste.value);PB.engine.load('pasted',parsed);pasteError.replaceChildren();select.selectedIndex=-1;PB.toast('Pasted plan evaluated.')}catch(e){pasteError.replaceChildren(U.error(e instanceof SyntaxError?'Enter valid JSON: an array of changes.':e.message))}},{'data-load-plan':''}),pasteError);
 function update(s){const focus=document.activeElement?.closest('[data-change-id]')?.dataset.changeId;banner.replaceChildren();if(!s.contract.confirmed)banner.append(h('div',{class:'inline-banner'},'No confirmed boundary — every change is DENY. ',L('Define one →','/contract')));contract.replaceChildren(C('CONTRACT / SAMPLE DATA'),h('h2',{},s.contract.environment),h('p',{class:'hash-line'},'contract: '+(s.contract.hash||'unconfirmed')),h('p',{class:'rule-reason'},s.contract.allowed.join(', ')),h('p',{class:'rule-reason'},'Max blast radius: '+s.contract.maxBlast),L('Edit →','/contract'));center.replaceChildren(C(s.changes.length+' CHANGES DETECTED / STATUS '+status(s)+' OF 3'),U.stepper(status(s)),...s.changes.map((c,i)=>row(c,i,ctx)));gate.classList.toggle('open',s.gateOpen);const excluded=s.changes.filter(c=>PB.engine.resolution(c.id)==='rejected').length;gate.replaceChildren(h('span',{class:'gate-symbol','aria-hidden':'true'},s.gateOpen?'↗':'⊣'),h('p',{class:'gate-status'},'GATE: '+(s.gateOpen?'OPEN':'CLOSED')),h('h3',{},'Ready to apply?'),h('p',{'data-gate-text':''},gateText(s)),B(s.appliedScope===PB.engine.scope()?'Applied (simulated)':'Apply Changes',()=>{if(PB.engine.apply()){PB.audio?.tick();PB.toast('Applied (simulated). Nothing was changed in infrastructure.')}},{class:'site-button primary',disabled:!s.gateOpen||s.appliedScope===PB.engine.scope(),'data-apply':''}),h('div',{class:'apply-set'},(s.changes.length-excluded)+' included · '+excluded+' rejected / excluded'),h('p',{class:'sample-tag'},'SAMPLE DATA · SIMULATED APPLY ONLY'));if(focus){const match=Array.from(center.querySelectorAll('[data-change-id]')).find(e=>e.dataset.changeId===focus);match?.focus({preventScroll:true})}}
 update(PB.store.get());ctx.subscribe(update);ctx.listen(companion,'pointerdown',()=>PB.robot?.acknowledge());ctx.listen(document,'keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const rows=Array.from(center.querySelectorAll('[data-change-id]'));let n=rows.indexOf(document.activeElement?.closest('[data-change-id]'));if(e.key==='j'||e.key==='k'){e.preventDefault();n=Math.max(0,Math.min(rows.length-1,n+(e.key==='j'?1:-1)));rows[n]?.focus()}else if(n>=0){const action={a:'approve',r:'reject',e:'explain'}[e.key];if(action){e.preventDefault();rows[n].querySelector('[data-action='+action+']')?.click()}}});return()=>{PB.lifecycle.robotTo(null);ctx.cleanup()};
});

register('/evidence','Evidence',(el,ctx)=>{
 el.className='subview';let filter='ALL',search='',selected=null,limit=24,lazy=null,chainCleanup=null;const heading=U.heading('The record behind the view.','EVIDENCE','Follow the chain from confirmed intent to each proposed change and its decision.'),host=h('div',{});el.append(heading,host);ctx.clean.push(()=>{lazy?.disconnect();chainCleanup?.()});
 const matches=()=>PB.store.get().records.filter(r=>(filter==='ALL'||(filter==='APPLIED'?r.event==='applied':r.verdict===filter))&&(r.change_0.resource+' '+r.change_0.rule).toLowerCase().includes(search.toLowerCase()));
 function detail(r){selected=r.id;lazy?.disconnect();chainCleanup?.();const chainCtx=PB.context();chainCleanup=()=>chainCtx.cleanup();host.replaceChildren(B('← Return to records',()=>{selected=null;list()},{'data-cursor':'BACK'}));const diagram=h('div',{class:'chain-diagram'}),canvas=U.signal('TRACE',chainCtx);diagram.append(C('INTENT → PLAN → VERDICT'),canvas,h('p',{class:'chain-label'},'01 INTENT / '+r.contract.hash),h('p',{class:'chain-label'},'02 PLAN / '+r.change_0.resource),U.badge(r.verdict));const total=(r.approval.intent_confirmed?1:0)+(r.approval.plan_evaluated?1:0)+(r.approval.human_resolved?1:0);host.append(h('div',{class:'evidence-detail'},diagram,h('div',{},C('RECORD #'+String(r.id).padStart(4,'0')+' / SAMPLE DATA'),U.json(r),C('APPROVAL STATUS '+total+' OF 3'),U.stepper(total))),actions(B('Copy JSON',()=>U.copy(r))));PB.a11y.announce('Evidence record '+r.id);}
 function list(){lazy?.disconnect();chainCleanup?.();host.replaceChildren();const all=matches(),grid=h('div',{class:'evidence-grid'}),count=C('TOTAL RECORDS '+PB.store.get().records.length+' / '+all.length+' MATCHING'),input=h('input',{class:'site-input',type:'search',value:search,'aria-label':'Search resource, name or rule',placeholder:'Search resource, name or rule',onInput:e=>{search=e.target.value;limit=24;renderTiles()}}),bar=h('div',{class:'filter-bar'},['ALL','ALLOW','REVIEW','DENY','APPLIED'].map(type=>B(type,()=>{filter=type;limit=24;list()},{class:'chip '+(filter===type?'selected':''),'aria-pressed':String(filter===type)})),input,B('Download JSON',()=>U.download(matches()),{'data-download':''}));host.append(count,bar,grid);const more=B('Load 24 more records',()=>{limit+=24;renderTiles()},{'data-more':''});host.append(more);
 function renderTiles(){const records=matches().slice().reverse();count.textContent='TOTAL RECORDS '+PB.store.get().records.length+' / '+records.length+' MATCHING';grid.replaceChildren();if(!records.length)grid.append(h('div',{class:'empty-state'},h('h2',{},'Nothing crossed this line.'),B('Clear filters',()=>{filter='ALL';search='';list()})));records.slice(0,limit).forEach(r=>{const tile=h('article',{class:'evidence-tile'},C('#'+String(r.id).padStart(4,'0')+' / SAMPLE DATA'),h('h3',{},r.change.resource),U.badge(r.event==='applied'?'APPLIED':r.verdict),h('div',{class:'evidence-meta'},r.change.name,h('br'),r.change_0.rule,h('br'),'contract: '+(r.contract.hash||'none').slice(0,6)+' · '+Math.max(0,Math.floor((Date.now()/1000-r.timestamp)/60))+' min ago'),B('Inspect record ↗',()=>detail(r),{'data-cursor':'INSPECT','data-record-id':r.id}));grid.append(tile)});more.hidden=records.length<=limit;}
 renderTiles();lazy=new IntersectionObserver(entries=>{if(entries[0].isIntersecting&&!more.hidden){limit+=24;renderTiles()}},{rootMargin:'100px'});lazy.observe(more);}
 ctx.subscribe(()=>{if(selected){const record=PB.store.get().records.find(r=>r.id===selected);if(record)detail(record);else list()}else list()});list();return()=>ctx.cleanup();
});

register('/how-it-works','How it works',(el,ctx)=>{
 el.className='subview';el.append(U.heading('One boundary. Three steps.','HOW IT WORKS','The agent proposes a plan. The confirmed boundary determines what may proceed.'));
 const steps=[['01 / DEFINE','Intent comes first.','Choose the environment, resource classes and blast-radius limit. Confirm that this boundary describes the task before inspecting a plan.',['Human defines scope','Confirmation locks the record','A hash identifies the boundary']],['02 / INSPECT','Every change is visible.','Compare each proposed change with the confirmed boundary. Inspect the matched rule and resolve only the changes that need human judgment.',['Normalize the proposed changes','Evaluate deterministic rules','Inspect ALLOW / REVIEW / DENY']],['03 / APPLY','The gate decides.','A DENY keeps the gate closed. Resolve all REVIEW items, then apply only the permitted set in this browser simulation.',['DENY cannot be approved away','Rejected changes are excluded','Every action leaves evidence']]];
 const scroll=h('section',{class:'how-scroll'}),sticky=h('div',{class:'how-sticky'}),copy=h('div',{class:'how-copy'}),diagram=h('canvas',{width:600,height:400,class:'how-diagram','aria-hidden':'true'}),buttons=h('div',{class:'how-steps'});sticky.append(h('div',{class:'how-layout'},copy,diagram),buttons);scroll.append(sticky);el.append(scroll);let current=-1,ratio=0,visible=true,last=0;const dc=diagram.getContext('2d');
 function show(k){if(k===current)return;current=k;copy.replaceChildren(C(steps[k][0]),h('h2',{},steps[k][1]),h('p',{},steps[k][2]),h('ul',{class:'how-list'},steps[k][3].map(x=>h('li',{},'— '+x))));buttons.replaceChildren(...steps.map((step,i)=>B(step[0],()=>{if(PB.reduced){show(i);draw(0)}else window.scrollTo({top:scroll.getBoundingClientRect().top+scrollY+(scroll.offsetHeight-innerHeight)*(i+.45)/3,behavior:'smooth'})},{class:'site-button '+(k===i?'primary':''),'aria-current':String(k===i)})));PB.a11y.announce('Step '+(k+1)+' of 3. '+steps[k][1]);}
 function measure(){const r=scroll.getBoundingClientRect();ratio=PB.clamp(-r.top/Math.max(1,scroll.offsetHeight-innerHeight));visible=r.bottom>0&&r.top<innerHeight;if(!PB.reduced)show(Math.min(2,Math.floor(ratio*3)))}
 function draw(t){dc.clearRect(0,0,600,400);dc.strokeStyle='#9eaa83';dc.lineWidth=2;dc.beginPath();const points=[[180,70],[420,70],[500,200],[420,330],[180,330],[100,200],[180,70]];const progress=current===0&&!PB.reduced?Math.min(1,.55+(t%4)/4):1;dc.moveTo(...points[0]);for(let i=1;i<points.length;i++){const amount=PB.clamp(progress*6-(i-1));if(amount>0)dc.lineTo(points[i-1][0]+(points[i][0]-points[i-1][0])*amount,points[i-1][1]+(points[i][1]-points[i-1][1])*amount)}dc.stroke();dc.font='12px monospace';dc.textAlign='center';dc.fillStyle='#aaa99f';dc.fillText('CONFIRMED BOUNDARY',300,48);if(current>=1){const colors=['#72e6a1','#f1c34f','#ff6f72'];for(let i=0;i<3;i++){const x=PB.reduced?200+i*90:80+((t*.12+i*.28)%1)*400;dc.fillStyle=x<110?'#aaa99f':colors[i];dc.beginPath();dc.arc(x,155+i*45,8,0,Math.PI*2);dc.fill()}}if(current===2){const open=PB.store.get().gateOpen;dc.strokeStyle=open?'#72e6a1':'#ff6f72';dc.lineWidth=5;dc.beginPath();dc.moveTo(500,160);dc.lineTo(open?540:500,open?125:240);dc.stroke();dc.fillStyle=dc.strokeStyle;dc.fillText('GATE: '+(open?'OPEN':'CLOSED'),300,370)}}
 show(0);ctx.listen(window,'scroll',measure,{passive:true});ctx.listen(window,'resize',measure,{passive:true});ctx.frame((dt,t)=>{if(!visible||t-last<1/30)return;if(PB.reduced&&last)return;last=t;draw(t)});ctx.subscribe(()=>draw(0));measure();el.append(h('section',{class:'agent-table'},h('div',{},C('THE AGENT MAY PROPOSE'),h('h3',{},'Possibilities.'),h('p',{},'Create, update, delete or replace infrastructure. Suggest a broad change set. Provide a plan for inspection.')),h('div',{},C('THE BOUNDARY DECIDES'),h('h3',{},'Permission.'),h('p',{},'Check the confirmed scope. Classify each change. Keep apply closed until all decisions are resolved.'))),actions(L('Try it →','/contract',{class:'site-button primary'})));return()=>ctx.cleanup();
});

register('/about','About',(el,ctx)=>{
 el.className='subview';el.append(U.heading('Why the boundary matters.','ABOUT PLANBOUND','A human sets the boundary. The agent works within it.'));const copy=h('div',{class:'editorial-copy'});PB.originalAbout.querySelectorAll(':scope > p,:scope > .pull').forEach(node=>copy.append(node.cloneNode(true)));
 const principles=[['Intent first','Confirm what the agent may change before inspecting its proposal. The authorization is explicit and belongs to the human.'],['Change by change','A plan is a collection of distinct decisions. Inspect each resource and the rule that explains its outcome.'],['Judgment only where needed','ALLOW is covered. REVIEW needs a decision. DENY stays blocked and cannot be approved away.'],['Auditable by default','Keep the contract, plan, verdict and resolution connected. Each record explains how a decision was reached.']];principles.forEach(([title,body],i)=>copy.append(h('section',{class:'principle'},C('0'+(i+1)),h('h3',{},title),h('p',{},body))));copy.append(h('section',{class:'principle'},h('h3',{},'What PlanBound is not'),h('ul',{},h('li',{},'Not another scoring layer.'),h('li',{},'Not a replacement for the reviewer.'),h('li',{},'Not an apply engine.'))));
 const faq=[['Does this site change infrastructure?','No. All site data is SAMPLE DATA. Apply writes a simulated event to this browser session.'],['What does the contract hash identify?','It identifies the serialized boundary fields. SHA-256 is used where available, with a labeled FNV-1a fallback.'],['Can a DENY be approved?','No. Change the proposed plan or define and confirm an appropriate boundary. DENY has no approval control.'],['What happens to a rejected REVIEW?','That change is excluded from the simulated apply set. It is an explicit human resolution, not an unresolved item.'],['Can I paste a Terraform plan directly?','This prototype accepts the normalized change-array shape shown in Evidence, not arbitrary raw Terraform plan JSON.'],['Where is my data stored?','The contract, sample-plan choice and scoped resolutions use sessionStorage when available. Evidence and pasted plan contents stay in memory. No data is sent to an application API.']];copy.append(h('section',{class:'faq'},h('h3',{},'Questions, answered.'),faq.map(([q,a])=>h('details',{},h('summary',{},q),h('p',{},a)))));el.append(h('div',{class:'editorial'},h('h2',{},'The agent can propose.'),copy),actions(L('Set the boundary →','/contract',{class:'site-button primary'})));return()=>ctx.cleanup();
});

register('/legal','Legal',(el,ctx)=>{
 el.className='subview';el.append(U.heading('A clear understanding.','LEGAL','PLACEHOLDER — replace before launch. This text describes the demonstration and is not production legal documentation.'));const content=h('div',{class:'legal-copy'}),tabs=h('div',{class:'site-actions'});for(const label of ['Terms','Privacy','Sample data'])tabs.append(B(label,()=>content.querySelector('[data-section="'+label+'"]').scrollIntoView({behavior:PB.reduced?'instant':'smooth',block:'start'})));el.append(tabs,content);
 content.append(h('section',{'data-section':'Terms'},C('PLACEHOLDER — REPLACE BEFORE LAUNCH'),h('h2',{},'Terms'),h('p',{},'This is an interactive demonstration of a boundary-review interface. Its sample decisions are not production authorization. You remain responsible for reviewing any real infrastructure changes in your own systems.'),h('p',{},'Before publishing a production service, replace this section with terms that describe the operator, actual features, support commitments and applicable jurisdiction.')),
 h('section',{'data-section':'Privacy'},C('PLACEHOLDER — REPLACE BEFORE LAUNCH'),h('h2',{},'Privacy'),h('p',{},'This demonstration does not send pasted plans or task notes to an application server. The current boundary, selected sample-plan identifier and scoped resolutions are kept in sessionStorage when the browser allows it. Pasted plan contents and evidence records stay in memory.'),h('p',{},'The page loads Three.js scripts and fonts from external CDNs. Those services receive ordinary asset requests. Replace this section before launch with a notice covering the actual hosting, analytics, retention and contact details.')),
 h('section',{'data-section':'Sample data'},C('SAMPLE DATA'),h('h2',{},'Nothing here is a real apply.'),h('p',{},'The sample plans, baseline counters and seeded records are illustrative. Browser-generated decisions and resolutions remain sample events. Apply records a simulated action; it does not execute Terraform or contact AWS.'),h('label',{class:'confirm-line'},h('input',{type:'checkbox',checked:!!PB.store.get().noticeDismissed,onChange:e=>PB.store.set({noticeDismissed:e.target.checked})}),h('span',{},'I UNDERSTAND. Dismiss the persistent sample-data footer notice for this open session.'))));return()=>ctx.cleanup();
});

register('/404','Outside the boundary',(el,ctx)=>{el.className='subview not-found';el.append(U.heading('Outside the boundary.','ROUTE NOT FOUND','This route is outside the site map. Return to the starting point.'),U.signal('DENY',ctx),actions(L('Return home →','/',{class:'site-button primary'})));return()=>ctx.cleanup()});
})();
