(function(){
'use strict';const PB=window.PB;
/** Construct DOM with text nodes; user input never passes through innerHTML. */
function h(tag,props,...children){const el=document.createElement(tag);for(const [key,value]of Object.entries(props||{})){if(key.startsWith('on'))el.addEventListener(key.slice(2).toLowerCase(),value);else if(key==='class')el.className=value;else if(key==='text')el.textContent=value;else if(value!==undefined&&value!==null){if(['checked','disabled','hidden','open','value','tabIndex'].includes(key))el[key]=value;else el.setAttribute(key,String(value))}}children.flat(Infinity).forEach(c=>{if(c!==null&&c!==undefined&&c!==false)el.append(c instanceof Node?c:document.createTextNode(String(c)))});return el}
PB.h=h;
/** Own all effects created by a mounted route. */
PB.context=()=>{const clean=[];return {clean,listen(el,event,fn,options){el.addEventListener(event,fn,options);clean.push(()=>el.removeEventListener(event,fn,options))},subscribe(fn){clean.push(PB.store.subscribe(fn))},frame(fn){clean.push(PB.frame(fn))},observe(el,fn){const io=new IntersectionObserver(fn);io.observe(el);clean.push(()=>io.disconnect());return io},timer(fn,ms){const id=setTimeout(fn,ms);clean.push(()=>clearTimeout(id));return id},cleanup(){clean.splice(0).reverse().forEach(f=>f())}}};
let toastTimer;
/** Announce a brief action result without stealing focus. */
PB.toast=msg=>{const el=document.getElementById('site-toast');el.textContent=msg;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true},3200)};
PB.a11y={announce(text){document.getElementById('route-live').textContent=text},focusMain(){document.getElementById('view').focus({preventScroll:true})}};
async function copy(obj){const text=JSON.stringify(obj,null,2);try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text)}else{const area=h('textarea',{value:text,'aria-label':'Copy JSON text',class:'copy-fallback'});document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();if(!ok)throw Error('Clipboard unavailable')}PB.toast('JSON copied.')}catch(e){PB.toast('Clipboard unavailable. Select the JSON text and copy it manually.')}}
function download(records){try{const blob=new Blob([JSON.stringify(records,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=h('a',{href:url,download:'planbound-evidence.json'});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);PB.toast('Downloaded '+records.length+' SAMPLE DATA records.')}catch(e){PB.toast('Download unavailable in this browser. Use Copy JSON on a record.')}}
const button=(text,fn,props={})=>h('button',{type:'button',class:'site-button',onClick:fn,...props},text);
const link=(text,path,props={})=>{const el=h('a',{href:'#'+path,class:'site-button','data-cursor':'NEXT',...props},text);el.classList.add('magnetic');return el};
const caption=text=>h('p',{class:'site-caption'},text);
/** Animate a real session metric only after its element enters the viewport. */
function counter(target,ctx){const el=h('strong',{},PB.reduced?target:0);let active=false,start=0,done=false;const io=ctx.observe(el,entries=>{if(entries[0].isIntersecting){active=true;io.disconnect()}});const off=PB.frame((dt,t)=>{if(!active||done)return;if(!start)start=t;const p=PB.reduced?1:Math.min(1,(t-start)/.8);el.textContent=Math.round(target*(1-Math.pow(1-p,3))).toLocaleString();if(p===1){done=true;off()}});ctx.clean.push(off);return el}
const badge=type=>h('button',{type:'button',class:'badge '+({ALLOW:'allow',REVIEW:'review-b',DENY:'deny',APPLIED:'allow'}[type]||''),'data-verdict':type.toLowerCase(),'data-cursor':'INSPECT',onPointerenter:()=>PB.bus.emit('verdict',type.toLowerCase()),onFocus:()=>PB.bus.emit('verdict',type.toLowerCase()),onClick:()=>PB.bus.emit('verdict',type.toLowerCase())},({ALLOW:'✓',REVIEW:'◇',DENY:'×',APPLIED:'✓'}[type]||'·')+' '+type);
function diff(before,after){return h('div',{class:'diff'},caption('PROPOSED CHANGE'),h('pre',{},h('span',{class:'line-del'},'- '+JSON.stringify(before,null,2)),h('span',{class:'line-add'},'+ '+JSON.stringify(after,null,2))))}
function stepper(current,total=3,labels=['Intent confirmed','Plan evaluated','Human resolved']){return h('div',{class:'site-stepper'},caption('STEP — '+String(current).padStart(2,'0')+' / '+String(total).padStart(2,'0')),h('div',{class:'step-chips'},labels.map((label,i)=>h('span',{class:i<current?'complete':''},String(i+1).padStart(2,'0')+' '+label))))}
function jsonNode(value,key,depth=0){if(value&&typeof value==='object'&&depth<8){const entries=Object.entries(value);return h('details',{class:'json-node',open:depth<2},h('summary',{},h('span',{class:'json-key'},key||'record'),Array.isArray(value)?' ['+entries.length+']':' {'+entries.length+'}'),entries.map(([k,v])=>jsonNode(v,k,depth+1)))}return h('div',{class:'json-value'},h('span',{class:'json-key'},key+': '),h('span',{class:typeof value==='string'?'json-string':'json-number'},JSON.stringify(value)))}
function json(obj){return h('div',{class:'site-json'},button('Copy JSON',()=>copy(obj),{'data-cursor':'INSPECT'}),jsonNode(obj,'record'))}
function heading(title,kicker,description){return h('header',{class:'view-heading'},h('a',{class:'return-link',href:'#/','data-cursor':'BACK'},'← Return to Home'),caption(kicker+' / SAMPLE DATA'),h('h1',{},title),description?h('p',{class:'view-lede'},description):null)}
function error(text){return h('div',{class:'site-error',role:'alert'},h('strong',{},'× Error Detected'),h('p',{},text))}
function toggleGroup(label,options,value,onchange){return h('fieldset',{class:'field'},h('legend',{},label),h('div',{class:'toggle-group'},options.map(option=>button(option,()=>onchange(option),{'aria-pressed':String(option===value),class:'chip '+(value===option?'selected':'')}))))}
/** Small 2D signal animation, capped at 30 fps and stopped by route cleanup. */
function signal(type,ctx){const canvas=h('canvas',{width:320,height:100,'aria-hidden':'true',class:'signal-canvas'}),c=canvas.getContext('2d');let visible=false,last=0;ctx.observe(canvas,entries=>visible=entries[0].isIntersecting);function draw(t){c.clearRect(0,0,320,100);const colors={DENY:'#ff6f72',REVIEW:'#f1c34f',ALLOW:'#72e6a1',TRACE:'#9eaa83'},color=colors[type];c.strokeStyle='#2a2c27';c.lineWidth=1;c.beginPath();c.moveTo(28,50);c.lineTo(290,50);c.stroke();c.fillStyle=color;c.strokeStyle=color;if(type==='DENY'){const x=PB.reduced?230:28+Math.min(1,(t%2)/1.4)*200;c.fillRect(x,46,25,8);c.fillRect(255,25,2,50)}else if(type==='REVIEW'){c.globalAlpha=PB.reduced?1:.55+.45*Math.sin(t*3);c.beginPath();c.arc(160,50,9,0,Math.PI*2);c.fill();c.globalAlpha=1}else if(type==='ALLOW'){c.beginPath();c.moveTo(28,50);c.lineTo(290,50);c.stroke()}else{for(const x of [35,160,285]){c.beginPath();c.arc(x,50,4,0,Math.PI*2);c.fill()}c.beginPath();c.arc(PB.reduced?160:35+(t*.15%1)*250,50,6,0,Math.PI*2);c.fill()}}
 ctx.frame((dt,t)=>{if(!visible||document.hidden||t-last<1/30||(PB.reduced&&last))return;last=t;draw(t)});return canvas}
PB.ui={h,button,link,caption,counter,badge,diff,stepper,json,heading,error,toggleGroup,copy,download,signal};
})();
