(function(){
'use strict';const PB=window.PB,U=PB.ui,h=PB.h,B=U.button,L=U.link,C=U.caption;
const home=document.getElementById('home-view'),host=document.getElementById('route-view'),main=document.getElementById('view');PB.originalAbout=document.querySelector('#home-view .about-copy').cloneNode(true);
document.querySelectorAll('body>.footer-word,body>footer').forEach(el=>el.remove());
const nav=document.querySelector('.site-nav'),links=[['How it works','/how-it-works'],['Contract','/contract'],['Plan Review','/plan-review'],['Evidence','/evidence'],['About','/about']];
const menu=h('dialog',{class:'menu-dialog','aria-label':'Site menu'}),menuClose=B('Close ×',()=>menu.close());menu.append(h('div',{class:'menu-top'},C('PLANBOUND / SITE MAP'),menuClose),h('div',{class:'menu-links'},[['Home','/'],...links,['Legal','/legal']].map(([title,path])=>h('a',{href:'#'+path,onClick:()=>menu.close()},title))));
nav.replaceChildren(h('a',{class:'brand',href:'#/'},h('i'),'PlanBound'),h('div',{class:'navlinks'},links.map(([name,path])=>h('a',{href:'#'+path},name))),h('div',{class:'nav-tools'},h('a',{class:'navcta magnetic',href:'#/plan-review'},'Review a plan'),B('Menu',()=>menu.showModal(),{'aria-haspopup':'dialog','aria-label':'Open site menu'})));
const status=h('a',{class:'nav-status',href:'#/contract','aria-label':'Boundary status'}),skip=h('a',{class:'skip-link',href:'#view',onClick:e=>{e.preventDefault();main.focus();}},'Skip to content'),live=h('div',{id:'route-live',class:'sr-only','aria-live':'polite','aria-atomic':'true'}),toast=h('div',{id:'site-toast',role:'status',hidden:true}),wipe=h('div',{class:'route-wipe','aria-hidden':'true'}),shortcuts=h('dialog',{class:'shortcut-dialog','aria-label':'Keyboard shortcuts'});
shortcuts.append(C('KEYBOARD SHORTCUTS'),h('p',{},'g then h / Home\ng then c / Contract\ng then p / Plan Review\ng then e / Evidence\ng then a / About\nM / Sound on or off\n? / This help\n\nIn Plan Review: j / k select a row, a approve, r reject, e explain.'),B('Close',()=>shortcuts.close()));document.body.prepend(skip);document.body.append(menu,shortcuts,status,live,toast,wipe);
const footer=h('footer',{class:'site-footer'},h('div',{class:'footer-columns'},h('div',{},C('PLANBOUND'),h('p',{},'Infrastructure changes, within intent.'),B('Return to top ↑',()=>window.scrollTo({top:0,behavior:PB.reduced?'instant':'smooth'}))),h('div',{},C('EXPLORE'),links.slice(0,3).map(([name,path])=>h('a',{href:'#'+path},name))),h('div',{},C('UNDERSTAND'),links.slice(3).map(([name,path])=>h('a',{href:'#'+path},name)),h('a',{href:'#/legal'},'Legal'))),h('div',{class:'footer-notice'},'SAMPLE DATA · This site simulates decisions and apply. Nothing is deployed. ',h('a',{href:'#/legal'},'Read the sample-data notice →')),h('div',{class:'footer-word','aria-hidden':'true'},'PLANBOUND'));document.body.append(footer);
const homeSlot=document.querySelector('#unit .studio-sticky');homeSlot.dataset.robotSlot='';
document.querySelectorAll('#home-view a[href^="#"]').forEach(a=>{const map={'#':'#/','#paths':'#/how-it-works','#review':'#/plan-review','#about':'#/about','#data':'#/evidence'};if(map[a.getAttribute('href')])a.setAttribute('href',map[a.getAttribute('href')])});
const paths=document.querySelector('#home-view .paths');paths.classList.add('home-paths');paths.replaceChildren(...[['01 / DEFINE','Set the boundary.','Choose what the agent may change. Confirm the environment and the scope.','/contract'],['02 / INSPECT','Read the decisions.','Inspect every change and the rule behind its verdict. Resolve the uncovered work.','/plan-review'],['03 / APPLY','Respect the gate.','Only the resolved set may proceed. The gate remains accountable to the boundary.','/how-it-works']].map(([step,title,body,path])=>h('article',{class:'path'},C(step),h('h2',{},title),h('p',{},body),L('Explore →',path))));
// Keep the base editorial sections, while replacing its static review data with live store rows.
const gallery=document.querySelector('#home-view .gallery');if(gallery)gallery.hidden=true;const signals=h('section',{class:'home-signals','aria-label':'Decision signals'}),counts=h('section',{class:'home-counts'}),cta=h('section',{class:'cta-band site-below'},C('SAMPLE DATA / EXPLORE THE WORKFLOW'),h('h2',{},'Set the boundary. Then let the agent run.'),h('div',{class:'site-actions'},L('Define a boundary →','/contract',{class:'site-button primary'}),L('Inspect a plan →','/plan-review')));paths.after(signals,counts,cta);
const oldReview=document.querySelector('#home-view .review');oldReview.className='home-preview site-below';
PB.open=index=>{const dialog=document.getElementById('feature-detail');document.getElementById('detail-title').textContent=PB.FEATURES[index].title;PB.renderJSON(document.getElementById('detail-json'),{sample_data:true,station:PB.FEATURES[index].n,contract:PB.store.get().contract,plan:PB.store.get().planId,verdicts:PB.store.get().verdicts,gate_open:PB.store.get().gateOpen});dialog.showModal()};
function updateShared(s){status.href=s.contract.confirmed?'#/plan-review':'#/contract';status.replaceChildren(h('span',{class:'gate-dot'+(s.gateOpen?' open':'')}),'BOUNDARY: '+(s.contract.confirmed?'CONFIRMED · '+s.contract.hash.slice(0,6):'NONE'));footer.querySelector('.footer-notice').hidden=!!s.noticeDismissed;const code=document.querySelector('#data pre');if(code)PB.renderJSON(code,{sample_data:true,contract:s.contract,plan_id:s.planId,plan_hash:s.planHash,verdicts:s.verdicts,gate_open:s.gateOpen});PB.record={sample_data:true,contract:s.contract,changes:s.changes,verdicts:s.verdicts,gate_open:s.gateOpen};}
PB.store.subscribe(updateShared);
function colorFor(resource){const s=PB.store.get(),c=s.changes.find(c=>c.resource===resource);return c?({ALLOW:0x72e6a1,REVIEW:0xf1c34f,DENY:0xff6f72}[s.verdicts[c.id].verdict]):0xaaa99f}
function wireTree(tree){const original=tree.update;tree.update=function(...args){original(...args);const s=PB.store.get();tree.gateMat.color.setHex(s.gateOpen?0x72e6a1:0xff6f72);if(s.gateOpen){tree.lock.visible=false;const count=tree.ringGeo.drawRange.count;tree.ringGeo.setDrawRange(0,Math.min(count,45));tree.gate.rotation.z=-.5;}if(tree.uniforms.uLeafColors){['aws_iam_role','aws_security_group','aws_s3_bucket'].forEach((type,i)=>tree.uniforms.uLeafColors.value[i].setHex(colorFor(type)))}if(PB.P>=.88){document.getElementById('station-number').textContent='BOUNDARY / '+(s.gateOpen?'OPEN':'CLOSED');document.getElementById('station-title').textContent=s.gateOpen?'Resolved. Ready to proceed.':'One path. A firm boundary.'}tree.storeGateOpen=s.gateOpen;};}
PB.bus.on('tree-ready',wireTree);
PB.siteViews.unshift({path:'/',title:'PlanBound — From change to confidence',mount(el,ctx){signals.replaceChildren();for(const [type,path]of [['DENY','/plan-review'],['REVIEW','/plan-review'],['ALLOW','/contract'],['TRACE','/evidence']])signals.append(h('a',{class:'signal-tile',href:'#'+path,'data-cursor':'OPEN'},C('SIGNAL / '+type),U.signal(type,ctx),h('h3',{},type),h('p',{class:'rule-reason'},({DENY:'A firm stop.',REVIEW:'A human decision.',ALLOW:'Within the boundary.',TRACE:'Follow the evidence.'}[type]))));
 function homeState(s){counts.replaceChildren(...[['PLANS EVALUATED',s.metrics.plansEvaluated],['CHANGES GATED',s.metrics.changesGated],['HUMAN DECISIONS',s.metrics.humanDecisions]].map(([label,n])=>h('div',{},C('SAMPLE DATA / SESSION'),U.counter(n,ctx),C(label))));oldReview.replaceChildren(C('SAMPLE DATA / LIVE SESSION'),h('h2',{class:'section-title'},'The plan, at a glance.'),h('p',{class:'rule-reason'},PB.gateText(s)),h('div',{class:'site-actions'},Object.entries(s.verdicts).map(([id,v])=>U.badge(v.verdict))),L('Open Plan Review →','/plan-review',{class:'site-button primary'}));}
 homeState(PB.store.get());ctx.subscribe(homeState);return()=>ctx.cleanup();}});

/** Hash router with serialized swaps, scoped cleanup and persistent Home nodes. */
PB.router=(()=>{const views=new Map();let cleanup=null,current=null,running=false,pending=false;const norm=hash=>(hash.replace(/^#/,'')||'/').replace(/\/+$/,'')||'/';
 function register(v){views.set(v.path,v)}
 async function swap(path){cleanup?.();cleanup=null;PB.lifecycle.robotTo(null);const v=views.get(path)||views.get('/404');host.replaceChildren();home.hidden=path!=='/';host.hidden=path==='/';const element=path==='/'?home:h('div',{});if(path!=='/')host.append(element);element.dataset.route=v.path;PB.lifecycle.route=path;const ctx=PB.context();cleanup=v.mount(element,ctx)||(()=>ctx.cleanup());current=path;document.title=v.title;window.scrollTo({top:0,behavior:'instant'});PB.scroll=0;PB.P=0;PB.targetProgress=0;PB.layoutDirty=true;PB.a11y.announce(v.title);PB.a11y.focusMain();nav.querySelectorAll('a').forEach(a=>a.setAttribute('aria-current',String(a.hash==='#'+path)));}
 async function render(){pending=true;if(running)return;running=true;try{while(pending){pending=false;const path=norm(location.hash);if(path===current)continue;if(!PB.started||PB.reduced){await swap(path)}else if(document.startViewTransition&&!['/','/plan-review'].includes(path)&&!['/','/plan-review'].includes(current)){const transition=document.startViewTransition(()=>swap(path));transition.ready.catch(()=>{});transition.updateCallbackDone.catch(()=>{});try{await transition.finished}catch(error){PB.transitionFallbacks=(PB.transitionFallbacks||0)+1;if(current!==path)await swap(path)}}else{wipe.textContent=({'/':'HOM','/contract':'CON','/plan-review':'PLN','/evidence':'EVD','/about':'ABT','/how-it-works':'HOW','/legal':'LEG'}[path]||'404');wipe.classList.add('cover');await new Promise(r=>setTimeout(r,350));await swap(path);await new Promise(r=>setTimeout(r,200));wipe.classList.remove('cover');await new Promise(r=>setTimeout(r,350))}PB.lifecycle.routeTo(path);PB.lifecycle.robotTo(path==='/'?homeSlot:host.querySelector('[data-robot-slot]'));PB.bus.emit('route',path);}}finally{running=false}}
 addEventListener('hashchange',render);return {register,go(path){location.hash='#'+path},render,get current(){return current},get busy(){return running}}})();
PB.siteViews.forEach(PB.router.register);
const bootStart=PB.boot.start.bind(PB.boot);PB.boot.start=audio=>{bootStart(audio);if(PB.started)PB.a11y.focusMain()};
let prefixUntil=0;document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.isContentEditable||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='?'){e.preventDefault();shortcuts.showModal();return}if(e.key.toLowerCase()==='g'){prefixUntil=performance.now()+1200;return}if(performance.now()<prefixUntil){prefixUntil=0;const route={h:'/',c:'/contract',p:'/plan-review',e:'/evidence',a:'/about'}[e.key.toLowerCase()];if(route){e.preventDefault();e.stopImmediatePropagation();PB.router.go(route)}}},true);
const resizeRobot=new ResizeObserver(()=>PB.robot?.resize?.());resizeRobot.observe(homeSlot);PB.bus.on('route',()=>{resizeRobot.disconnect();if(PB.lifecycle.robotSlot)resizeRobot.observe(PB.lifecycle.robotSlot)});
// Permit the boot screen to paint before either WebGL factory is invoked.
requestAnimationFrame(()=>requestAnimationFrame(async()=>{await PB.engine.init();await PB.router.render();if(PB.lifecycle.route!=='/'){for(const key of ['context','lattice','links','tree','shaders'])PB.boot.complete(key,'Home '+key+' deferred until first visit');if(!PB.robot)PB.boot.complete('robot','Reviewer deferred until a view requests it');}if(PB.restoreNotice)PB.toast(PB.restoreNotice);PB.siteReady=true;}));
})();
